"""car_id set unique

Revision ID: 0a356bdbaafe
Revises: 0c93b4cc073c
Create Date: 2026-05-05 10:43:40.110049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a356bdbaafe'
down_revision: Union[str, Sequence[str], None] = '0c93b4cc073c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'rental_requests', ['car_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rental_requests', type_='unique')
    # ### end Alembic commands ###
