"""nullable False

Revision ID: 0c93b4cc073c
Revises: 9e36322ebbf3
Create Date: 2026-05-04 18:06:49.625395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c93b4cc073c'
down_revision: Union[str, Sequence[str], None] = '9e36322ebbf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('iot_devices', 'car_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('iot_devices', 'car_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
