"""add document

Revision ID: 8ee4aa9b3fad
Revises: e570dc86843c
Create Date: 2026-04-26 10:21:13.158052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee4aa9b3fad'
down_revision: Union[str, Sequence[str], None] = 'e570dc86843c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_type', sa.Enum('public_offer', 'driver_offer', name='document_type_enum'), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='Путь к файлу в MinIO (bucket/path/file.pdf)'),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='Размер файла в байтах'),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Актуальная версия документа'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='Дата публикации документа'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###
